<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsqTSTb\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsqTSTb/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCsqTSTb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCsqTSTb\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerCsqTSTb\srcApp_KernelProdContainer([
    'container.build_hash' => 'CsqTSTb',
    'container.build_id' => '44e144b7',
    'container.build_time' => 1617914410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsqTSTb');
