<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \App\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Id_cours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'nom_cours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'domaine', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'lien', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'lien2'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'Id_cours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'nom_cours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'domaine', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'lien', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'lien2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId_cours(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId_cours', []);

        return parent::getId_cours();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCours(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCours', []);

        return parent::getNomCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCours(string $nom_cours): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCours', [$nom_cours]);

        return parent::setNomCours($nom_cours);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaine(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaine', []);

        return parent::getDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaine(string $domaine): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaine', [$domaine]);

        return parent::setDomaine($domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getLien(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLien', []);

        return parent::getLien();
    }

    /**
     * {@inheritDoc}
     */
    public function setLien(string $lien): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLien', [$lien]);

        return parent::setLien($lien);
    }

    /**
     * {@inheritDoc}
     */
    public function getLien2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLien2', []);

        return parent::getLien2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLien2(string $lien2): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLien2', [$lien2]);

        return parent::setLien2($lien2);
    }

}
